const screens=[...document.querySelectorAll(".screen")];function show(id){screens.forEach(s=>s.hidden=s.id!==id);window.scrollTo(0,0)}document.addEventListener("click",e=>{let b=e.target.closest("[data-go]");if(b)show(b.dataset.go)});
const regionData={heat:{title:"Pacific Northwest extreme heat",text:"Late June 2021 brought extraordinary heat across the Pacific Northwest, with temperatures far beyond the region’s historical experience.",rating:"STRONG",needle:"90%",why:"Human-caused warming is increasing the likelihood and intensity of extreme heat.",link:"https://www.worldweatherattribution.org/western-north-american-extreme-heat-virtually-impossible-without-human-caused-climate-change/",cls:"heat-visual"},rain:{title:"Tennessee heavy rainfall",text:"In August 2021, exceptionally heavy rainfall produced devastating flash flooding in Middle Tennessee.",rating:"STRONG",needle:"82%",why:"A warmer atmosphere can hold more moisture, and observations show increases in heavy precipitation, although climate change does not explain every individual flood.",link:"https://www.epa.gov/climatechange-science/extreme-precipitation",cls:"rain-visual"}};
document.querySelectorAll("[data-region]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-region]").forEach(x=>x.classList.toggle("active",x===b));let d=regionData[b.dataset.region];regionTitle.textContent=d.title;regionText.textContent=d.text;regionRating.textContent=d.rating;regionNeedle.style.left=d.needle;regionWhy.textContent=d.why;regionScience.href=d.link;regionVisual.className="event-visual "+d.cls});
const seasons={
winter:{title:"Winter: damaging ice storm",text:"In February 2021, freezing rain coated parts of the Willamette Valley in ice, damaging trees and disrupting power.",status:"EXTREME EVENT",fact:"This was a damaging, unusual winter weather event.",rating:"UNCERTAIN",ratingCls:"",needle:"20%",event:"Uncertain",future:"Uncertain",why:"The science is not clear about how climate change influenced this particular ice storm. Future changes in damaging ice storms in the Willamette Valley are also uncertain because these events are relatively uncommon and the processes that create them are complex.",cls:"winter",label:"ICE STORM",link:"https://www.climate.gov/"},
spring:{title:"Spring: exceptional dryness",text:"Spring 2021 was exceptionally dry across the Pacific Northwest, including Oregon.",status:"EXTREME CONDITIONS",fact:"Oregon, Washington, and Idaho recorded their second-driest spring since 1895, receiving about 45% of normal spring precipitation.",rating:"MODERATE",ratingCls:"moderate",needle:"58%",event:"Multiple drivers",future:"Increasing drying risk",why:"The extreme dryness was real, but drought develops from several interacting factors. Warming can increase evaporative demand, accelerate snowmelt, and intensify dry conditions; precipitation variability also remains important.",cls:"spring",label:"EXCEPTIONAL DRYNESS",link:"https://www.drought.gov/drought-status-updates/drought-status-update-pacific-northwest-2021-07-08"},
summer:{title:"Summer: record-shattering heat",text:"In late June 2021, extraordinary heat spread across the Pacific Northwest, including the Willamette Valley.",status:"EXTREME EVENT",fact:"Portland reached 116°F on June 28, breaking its previous all-time temperature record.",rating:"STRONG",ratingCls:"strong",needle:"91%",event:"Strong evidence",future:"Increasing heat risk",why:"Attribution research found that heat of this magnitude would have been virtually impossible without human-caused climate change. Continued warming makes severe heat more likely and more intense.",cls:"summer",label:"EXTREME HEAT",link:"https://www.worldweatherattribution.org/western-north-american-extreme-heat-virtually-impossible-without-human-caused-climate-change/"},
fall:{title:"Fall: wet weather returns",text:"Wet weather returned during fall 2021 after the exceptionally dry spring and hot summer.",status:"NO EXTREME EVALUATED",fact:"We are not identifying a specific Willamette Valley extreme event to evaluate for this season.",rating:"N/A",ratingCls:"na",needle:"0%",event:"N/A",future:"N/A",why:"No specific extreme event is being evaluated, so a climate-attribution or future-risk rating is not appropriate.",cls:"fall",label:"WET WEATHER",link:"https://www.drought.gov/"}
};
document.querySelectorAll("[data-season]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-season]").forEach(x=>x.classList.toggle("active",x===b));let d=seasons[b.dataset.season];seasonTitle.textContent=d.title;seasonText.textContent=d.text;seasonStatus.textContent=d.status;seasonStatus.className="status-pill "+(d.rating==="N/A"?"context":"");seasonFact.querySelector("p").innerHTML="<b>What the weather record tells us</b><br>"+d.fact;seasonRating.textContent=d.rating;seasonRating.className=d.ratingCls;seasonNeedle.style.left=d.needle;eventInfluence.textContent=d.event;futureRisk.textContent=d.future;seasonWhy.textContent=d.why;seasonScience.href=d.link;seasonVisual.className="season-visual "+d.cls;seasonVisualLabel.textContent=d.label;document.querySelector(".mini-scale").style.visibility=d.rating==="N/A"?"hidden":"visible"});
const big={heat:{icon:"☀️",mt:"A warmer baseline changes the odds",mx:"As average temperatures rise, extreme-heat thresholds are reached more often and the hottest events can become more intense.",dt:"Extreme heat is becoming more common",dx:"Long-term observations show increases in extreme heat across much of the United States, including the Northwest.",link:"https://www.epa.gov/climate-indicators/climate-change-indicators-high-and-low-temperatures"},rain:{icon:"🌧️",mt:"Warmer air can supply more moisture",mx:"A warmer atmosphere can hold more water vapor, increasing the potential for heavier precipitation when storms develop.",dt:"Heavy precipitation has increased in many regions",dx:"Long-term U.S. observations show that a larger share of precipitation is falling in very heavy events, with substantial regional differences.",link:"https://www.epa.gov/climate-indicators/climate-change-indicators-heavy-precipitation"}};
document.querySelectorAll("[data-big]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-big]").forEach(x=>x.classList.toggle("active",x===b));let d=big[b.dataset.big];mechanismIcon.textContent=d.icon;mechanismTitle.textContent=d.mt;mechanismText.textContent=d.mx;dataTitle.textContent=d.dt;dataText.textContent=d.dx;bigScience.href=d.link});
const decisions=[
{hazard:"EXTREME HEAT",icon:"☀️",claim:"Should extreme summer heat be a long-term preparedness priority for Willamette Valley gardens?",context:"Use the regional heat evidence to decide whether the risk is increasing enough to justify long-term preparation.",strength:"strong",prep:"yes",title:"Long-term heat evidence",text:"Observed warming and extreme-heat evidence for the Pacific Northwest show an increasing heat risk. Attribution research also found a strong human-caused climate influence on the 2021 heat event.",source:"https://www.epa.gov/climate-indicators/climate-change-indicators-high-and-low-temperatures",bars:[28,35,31,42,48,55,62,74,82,94],feedback:"The evidence supports increasing extreme-heat risk. Long-term preparation for heat is justified."},
{hazard:"SEVERE ICE STORMS",icon:"🧊",claim:"Should increasingly frequent severe ice storms be a long-term climate preparedness priority for Willamette Valley gardens?",context:"A damaging ice storm occurred in 2021. Decide whether that event is enough to support a claim of increasing future risk.",strength:"uncertain",prep:"notyet",title:"What the evidence can—and cannot—tell us",text:"The 2021 ice storm was a real extreme event, but the science is not clear about how climate change influenced that storm. Future changes in damaging Willamette Valley ice storms are also uncertain because the events are uncommon and involve complex conditions.",source:"https://www.climate.gov/",bars:[52,37,65,28,59,42,70,34,61,45],feedback:"The event was extreme, but evidence for climate influence and increasing future frequency remains uncertain. General ice-storm preparedness can still be useful, but the evidence does not justify describing increasingly frequent ice storms as an established climate trend."},
{hazard:"HEAVY PRECIPITATION",icon:"🌧️",claim:"Should very heavy precipitation be a long-term preparedness priority for Willamette Valley gardens?",context:"This time, don't rely on the Southeast example. Examine the regional evidence and decide what it supports for the Willamette Valley.",strength:"uncertain",prep:"yes",title:"Pacific Northwest heavy-precipitation evidence",text:"Regional evidence shows that heavy precipitation can increase as the atmosphere warms, but trends and projections vary by location and metric. Use the regional pattern—not the Southeast result—to judge how confidently the Willamette Valley conclusion can be stated.",source:"https://nca2023.globalchange.gov/chapter/27/",bars:[35,42,38,47,44,55,49,61,57,66],feedback:"The regional evidence supports considering heavier precipitation in preparedness, while retaining more uncertainty than for extreme heat. Garden responses can include drainage, soil protection, and managing saturated conditions."}
];let di=0;
function drawEvidence(d){evidenceVisual.className="evidence-visual "+(di===1?"uncertain":di===2?"rain":"");evidenceVisual.innerHTML=d.bars.map(v=>'<i style="height:'+v+'%"></i>').join("")}
function resetCurrent(){document.querySelectorAll('input[name="strength"],input[name="prep"]').forEach(x=>x.checked=false);check.disabled=true;check.hidden=false;feedback.hidden=true;retryActions.hidden=true;next.hidden=true}
function render(){let d=decisions[di];challengeNum.textContent="DECISION "+(di+1)+" OF 3";hazardIcon.textContent=d.icon;hazardLabel.textContent=d.hazard;claim.textContent=d.claim;context.textContent=d.context;evidenceTitle.textContent=d.title;evidenceText.textContent=d.text;evidenceSource.href=d.source;drawEvidence(d);evidenceDrawer.hidden=true;reviewEvidence.setAttribute("aria-expanded","false");reviewEvidence.querySelector("span").textContent="+";resetCurrent();document.querySelectorAll(".dot").forEach((x,i)=>{x.classList.toggle("active",i===di);x.classList.toggle("done",i<di)})}
function toggleEvidence(open){evidenceDrawer.hidden=!open;reviewEvidence.setAttribute("aria-expanded",String(open));reviewEvidence.querySelector("span").textContent=open?"−":"+"}
reviewEvidence.onclick=()=>toggleEvidence(evidenceDrawer.hidden);
document.querySelectorAll('input[name="strength"],input[name="prep"]').forEach(x=>x.onchange=()=>{check.disabled=!(document.querySelector('input[name="strength"]:checked')&&document.querySelector('input[name="prep"]:checked'))});
check.onclick=()=>{let d=decisions[di],s=document.querySelector('input[name="strength"]:checked').value,p=document.querySelector('input[name="prep"]:checked').value,ok=s===d.strength&&p===d.prep;feedback.hidden=false;feedback.classList.toggle("caution",!ok);feedback.innerHTML=(ok?"<b>Your reasoning fits the evidence.</b> ":"<b>Take another look at the evidence.</b> ")+d.feedback;check.hidden=true;if(ok){next.hidden=false}else{retryActions.hidden=false}};
resetDecision.onclick=resetCurrent;retry.onclick=resetCurrent;reviewAgain.onclick=()=>toggleEvidence(true);
next.onclick=()=>{di++;if(di<decisions.length)render();else{challengeCard.hidden=true;complete.hidden=false}};
restartChallenge.onclick=()=>{di=0;challengeCard.hidden=false;complete.hidden=true;render()};
document.querySelector('[data-go="challenge"]').addEventListener("click",()=>{di=0;challengeCard.hidden=false;complete.hidden=true;render()});render();