const screens=[...document.querySelectorAll('.screen')];function openScreen(id){document.querySelector('.hero').style.display=id==='start'?'grid':'none';screens.forEach(s=>{s.hidden=s.id!==id});document.querySelectorAll('iframe').forEach(f=>f.remove());window.scrollTo(0,0)}document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.open)));
const events={pnw:{place:'PACIFIC NORTHWEST · JUNE 2021',title:'Extreme heat',text:'A persistent heat dome pushed temperatures far beyond typical early-summer conditions across the Pacific Northwest.',video:'TcU8YNYQmGg'},tn:{place:'WAVERLY, TENNESSEE · AUGUST 2021',title:'Extreme rainfall',text:'Exceptionally heavy rainfall produced extreme flash flooding. More than 20 inches was recorded within 24 hours near the event area.',video:'gDvWd8uphXk'}};let currentEvent='pnw';document.querySelectorAll('.event-postcard').forEach(b=>b.addEventListener('click',()=>{currentEvent=b.dataset.event;document.querySelectorAll('.event-postcard').forEach(x=>x.classList.toggle('active',x===b));let e=events[currentEvent];eventPlace.textContent=e.place;eventTitle.textContent=e.title;eventText.textContent=e.text;videoBox.innerHTML='';eventVideo.textContent='▶ Watch event video';if(imageNote)imageNote.hidden=currentEvent!=='pnw';eventClimateButton.textContent=currentEvent==='pnw'?'See the heat climate connection →':'See the precipitation climate connection →'}));eventVideo.addEventListener('click',()=>{if(videoBox.innerHTML){videoBox.innerHTML='';eventVideo.textContent='▶ Watch event video'}else{videoBox.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${events[currentEvent].video}" title="Event video" allowfullscreen></iframe>`;eventVideo.textContent='Hide video'}});

const seasonData=[
{cls:'winter',month:'WINTER · FEBRUARY 2021',title:'Major ice storm',text:'A major ice storm affected parts of the Willamette Valley. Freezing rain accumulated on trees, roads, and power lines, creating a damaging winter extreme.',evidence:'Same region, winter conditions: precipitation fell while surface temperatures were cold enough for ice to build up.',poster:'winter-poster.jpg',video:'winter.mp4'},
{cls:'spring',month:'SPRING · MARCH–MAY 2021',title:'Exceptionally dry spring',text:'Spring turned unusually warm and dry. By April 19, precipitation across the Willamette was about 80% of normal, and rapid spring snowmelt followed.',evidence:'Willamette Basin snow-water equivalent fell from 118% of normal on April 1 to 45% by May 13.',poster:'spring-poster.jpg',video:'spring.mp4'},
{cls:'summer',month:'SUMMER · JUNE 2021',title:'Record-breaking extreme heat',text:'The late-June heat wave pushed temperatures far beyond the normal range across the Willamette Valley. Portland reached 116°F and Salem reached 117°F on June 28.',evidence:'Same region, summer conditions: an exceptional heat event replaced the cold-season hazards seen only months earlier.',poster:'summer-poster.jpg',video:'summer.mp4'},
{cls:'fall',month:'FALL · SEPTEMBER 2021',title:'Rain returns',text:'A series of atmospheric rivers brought substantial precipitation back to Oregon and the Pacific Northwest during the second half of September.',evidence:'Same region, fall conditions: the seasonal shift brought cooler, wetter weather after the exceptionally dry spring and hot summer.',poster:'fall-poster.jpg',video:'fall.mp4'}
];document.querySelectorAll('.season-card').forEach((b,i)=>b.addEventListener('click',()=>{let s=seasonData[i];document.querySelectorAll('.season-card').forEach(x=>x.classList.toggle('active',x===b));seasonFeatureImage.className='feature-image '+s.cls;seasonPoster.src=s.poster;seasonLoop.poster=s.poster;if(s.video){seasonLoop.src=s.video;seasonFeatureImage.classList.add('has-video');seasonLoop.play().catch(()=>seasonFeatureImage.classList.remove('has-video'))}else{seasonLoop.removeAttribute('src');seasonLoop.load();seasonFeatureImage.classList.remove('has-video')}seasonMonth.textContent=s.month;seasonTitle.textContent=s.title;seasonText.textContent=s.text;seasonEvidence.innerHTML=s.evidence}));

document.querySelectorAll('.hazard-choice-btn').forEach(btn=>btn.addEventListener('click',()=>{
  document.querySelectorAll('.hazard-choice-btn').forEach(b=>{
    const on=b===btn;
    b.classList.toggle('active',on);
    b.setAttribute('aria-selected',String(on));
  });
  document.querySelectorAll('.big-hazard-view').forEach(v=>v.classList.remove('active'));
  document.querySelector('#'+btn.dataset.hazard+'BigView').classList.add('active');
}));
openScreen('start');

eventClimateButton.addEventListener('click',()=>{
  openScreen('climate');
  const target=currentEvent==='pnw'?'heat':'rain';
  document.querySelectorAll('.climate-view').forEach(v=>v.classList.remove('active'));
  document.querySelector('#'+target+'Visual').classList.add('active');

  const label=document.querySelector('#climatePathLabel');
  if(label){
    label.textContent = target==='heat'
      ? 'Extreme heat: how a warmer baseline changes the odds.'
      : 'Heavy precipitation: how warmer air can increase available moisture.';
  }
});


const eventEvidenceData={pnw:{rating:'STRONG',cls:'strong',needle:'88%',text:'Human-caused warming made the 2021 Pacific Northwest heat wave far more likely and more intense.',link:'https://www.worldweatherattribution.org/western-north-american-extreme-heat-virtually-impossible-without-human-caused-climate-change/'},tn:{rating:'STRONG',cls:'strong',needle:'82%',text:'There is strong evidence that human-caused warming has contributed to increases in heavy precipitation, although climate change does not explain every individual flood.',link:'https://www.epa.gov/climatechange-science/extreme-precipitation'}};
function updateEventEvidence(){let d=eventEvidenceData[currentEvent]||eventEvidenceData.pnw;if(!document.querySelector('#eventEvidenceRating'))return;eventEvidenceRating.textContent=d.rating;eventEvidenceRating.className='rating '+d.cls;eventEvidenceNeedle.style.left=d.needle;eventEvidenceText.textContent=d.text;eventEvidenceLink.href=d.link}
document.querySelectorAll('[data-event]').forEach(b=>b.addEventListener('click',()=>setTimeout(updateEventEvidence,0)));updateEventEvidence();
const seasonEvidenceData=[{rating:'QUESTIONABLE',cls:'questionable',needle:'20%',text:'Climate change is altering winter conditions, but evidence is not strong enough to conclude that damaging Willamette Valley ice storms will become more frequent.',link:'https://www.climate.gov/'},{rating:'MODERATE',cls:'moderate',needle:'60%',text:'The 2021 dry spring was a real regional extreme. Warming contributes to earlier snowmelt and greater drying, while precipitation variability remains important.',link:'https://www.drought.gov/drought-status-updates/drought-status-update-pacific-northwest'},{rating:'STRONG',cls:'strong',needle:'90%',text:'Human-caused warming is increasing the likelihood and intensity of extreme heat in the Pacific Northwest.',link:'https://www.worldweatherattribution.org/western-north-american-extreme-heat-virtually-impossible-without-human-caused-climate-change/'},{rating:'QUESTIONABLE',cls:'questionable',needle:'25%',text:'Rain returned in fall 2021, but this seasonal event alone is not evidence that comparable fall storms will become more frequent.',link:'https://www.drought.gov/drought-status-updates/drought-status-update-pacific-northwest-2021-09-24'}];
document.querySelectorAll('.season-card').forEach((b,i)=>b.addEventListener('click',()=>{let d=seasonEvidenceData[i];if(!d||!document.querySelector('#seasonEvidenceRating'))return;seasonEvidenceRating.textContent=d.rating;seasonEvidenceRating.className='rating '+d.cls;seasonEvidenceNeedle.style.left=d.needle;seasonClimateText.textContent=d.text;seasonScienceLink.href=d.link}));
const decisions=[{claim:'A Willamette Valley garden group should make extreme summer heat a priority in its long-term preparedness guidance.',context:'Consider the 2021 heat event, attribution evidence, and long-term warming.',min:70,prep:'yes',feedback:'The evidence is strong. Human-caused warming made the 2021 Pacific Northwest heat wave much more likely and more intense. Planning for heat stress, shade, irrigation reliability, and gardener safety is justified.'},{claim:'Gardeners should redesign their landscapes specifically because severe Willamette Valley ice storms are expected to become more frequent.',context:'The February 2021 ice storm was damaging and memorable. Does that establish an increasing climate-driven risk?',max:40,prep:'notyet',feedback:'A severe event can justify general emergency preparedness, but current evidence does not support a confident claim that damaging Willamette Valley ice storms will become more frequent because of climate change.'},{claim:'Garden preparedness guidance should account for heavier precipitation where regional climate evidence shows it is increasing.',context:'Think about the physical mechanism and long-term observations rather than any single flood.',min:65,prep:'yes',feedback:'This is supported where regional evidence shows increasing heavy precipitation. The appropriate garden response should still be tailored to local evidence and drainage conditions.'}];
let decisionIndex=0;const dc=document.querySelector('#decisionCard'),complete=document.querySelector('#decisionComplete');
function renderDecision(){let d=decisions[decisionIndex];decisionKicker.textContent='DECISION '+(decisionIndex+1);decisionClaim.textContent=d.claim;decisionContext.textContent=d.context;evidenceSlider.value=50;document.querySelectorAll('input[name="prep"]').forEach(x=>x.checked=false);checkDecision.disabled=true;checkDecision.hidden=false;decisionFeedback.hidden=true;nextDecision.hidden=true;document.querySelectorAll('.decision-dot').forEach((x,i)=>{x.classList.toggle('active',i===decisionIndex);x.classList.toggle('done',i<decisionIndex)})}
document.querySelectorAll('input[name="prep"]').forEach(x=>x.addEventListener('change',()=>checkDecision.disabled=false));
checkDecision.addEventListener('click',()=>{let d=decisions[decisionIndex],v=+evidenceSlider.value,prep=document.querySelector('input[name="prep"]:checked')?.value,meterOK=d.max!==undefined?v<=d.max:v>=d.min,ok=meterOK&&prep===d.prep;decisionFeedback.hidden=false;decisionFeedback.classList.toggle('caution',!ok);decisionFeedback.innerHTML=(ok?'<b>Your judgment matches the strength of the evidence.</b> ':'<b>Compare your conclusion with the evidence.</b> ')+d.feedback;checkDecision.hidden=true;nextDecision.hidden=false});
nextDecision.addEventListener('click',()=>{decisionIndex++;if(decisionIndex<decisions.length)renderDecision();else{dc.hidden=true;complete.hidden=false}});
document.querySelectorAll('[data-open="knowledge"]').forEach(b=>b.addEventListener('click',()=>{decisionIndex=0;dc.hidden=false;complete.hidden=true;renderDecision()}));
